### ISSUE TITLE
Title: Fix the responsiveness and color combination of header

### ISSUE THREAD

**Issue by nishu91020** [CatsInTech/Rezume#97] opened 2022-03-05 16:51 UTC
### Is your feature request related to a problem? Please describe.

Hi, I'm a contributor at GSSOC '22, I would like to add the following features-
1) Make the header responsive i.e, convert it into a hamburger menu on small screens.
2) make the background of the about us button such that it matches the theme.

**Comment by praveenscience** [comment] 2022-03-05 18:04
Hi @nishu91020 What do you think of this issue: #72? Is it not a duplicate?

**Comment by nishu91020** [comment] 2022-03-06 05:58
oh yes, it is, @praveenscience so can I continue working on this issue, or you can assign me some other issue to work on.

**Comment by rohitkhicher001** [comment] 2022-03-18 08:44
I would like to contribute as a gssoc'22 contributor and solve this issue.

**Comment by praveenscience** [comment] 2022-03-27 18:33
@rohitkhicher001 This is a dupe of #72. Why didn't you see the above comment?

**Closed by praveenscience** 2022-03-27 18:33 UTC
