### ISSUE TITLE
Title: Download button/ routing feature. 

### ISSUE THREAD

**Issue by SonikeshKumar14** [CatsInTech/Rezume#89] opened 2022-03-03 19:09 UTC
### Is your feature request related to a problem? Please describe.

I want to add Download button and routing feature.

### Describe the solution you'd like.

I can add download button so that we can get Pdf of resume 
and routing feature to responsive 

### Describe alternatives you've considered.

for download button It can be do by using  node js  and routing feature by using react router dom

### Add any other context or screenshots about the feature request here.

![Screenshot_2022-03-04_00-16-43](https://user-images.githubusercontent.com/91758635/156633029-227c6188-ccc9-446b-aed2-61aec221ca9b.png)

**Comment by bhuvan2002** [comment] 2022-03-03 20:03
Hello, Please assign it to me as I am GSSOC contributor

**Comment by Anirban-1490** [comment] 2022-03-04 07:02
this is a duplicate issue i think #86

**Comment by praveenscience** [comment] 2022-03-04 15:22
Dupe of #86

**Closed by praveenscience** 2022-03-04 15:22 UTC
