### ISSUE TITLE
Add the experience ,education and award section 

### ISSUE THREAD

**Issue by Sandhya312** [CatsInTech/Rezume#73] opened 2022-03-01 16:16 UTC
**I am a contributor of GSSOC'22**
**I want to add some sections like experience, education, and award.**
There is mention only the name of the section but we can't add them in the resume so I want to fix this.

![experience](https://user-images.githubusercontent.com/85842071/156210243-14e24f74-b95c-45dc-bcdf-eee46e77ab60.png)

**Comment by praveenscience** [comment] 2022-03-03 09:16
Hey @Sandhya312, let's start working on this.

**Comment by praveenscience** [comment] 2022-03-10 13:50
Any updates @Sandhya312? This is technically a dupe of #15. But was waiting for you to complete this.

**Comment by Sandhya312** [comment] 2022-03-10 14:50
> Any updates @Sandhya312? This is technically a dupe of #15. But was waiting for you to complete this.

I am working on this issue. If I will fail to complete then I will inform you by tomorrow.

**Comment by praveenscience** [comment] 2022-03-10 15:19
@mayonk-kumar-git Let's wait for her... Thanks for the update @Sandhya312! 👍🏻

**Comment by Sandhya312** [comment] 2022-03-11 06:13
Hey, @praveenscience You can assign this issue to anyone.

**Comment by mayonk-kumar-git** [comment] 2022-03-11 07:30
@praveenscience I am always ready😁

**Comment by praveenscience** [comment] 2022-03-11 09:40
What happened @Sandhya312?

**Comment by Sandhya312** [comment] 2022-03-11 12:12
> What happened @Sandhya312?

Actually, I am also busy in my college and don't want to waste the time of anyone.

**Closed** 2022-05-30 11:29 UTC
