### ISSUE TITLE
Adding a sidebar to edit experience and awards section 

### ISSUE THREAD

**Issue by harsh5902** [CatsInTech/Rezume#107] opened 2022-03-10 07:06 UTC
### What happened?

As we see in About section of Rezume there is an a sidebar for editing which reflect the our edits on the main resume.
![image](https://user-images.githubusercontent.com/74867899/157606998-33027568-0252-4532-80f2-1046f3a559ff.png)
But in Awards, Experience and other section have nothing which we edit for
![image](https://user-images.githubusercontent.com/74867899/157607285-bca7be01-d6ac-4d61-a5e1-1682bfc0ef57.png)

### How can we reproduce this bug?

I will add editing sidebar so that we can add our experience and awards.

**Comment by praveenscience** [comment] 2022-03-10 13:15
Have you checked for dupes? @harsh5902?

**Comment by praveenscience** [comment] 2022-03-10 13:18
Yep, dupe of #12 and #13...

**Closed by praveenscience** 2022-03-10 13:18 UTC
