### ISSUE TITLE
Node Sass version 7.0.0 is incompatible with ^4.0.0

### ISSUE THREAD

**Issue by rithgan** [CatsInTech/Rezume#110] opened 2022-03-11 06:32 UTC
### What happened?

After running npm start

![Incompatible version of node-sass](https://user-images.githubusercontent.com/39555302/157812834-4977216c-8206-44a2-aa74-6b71309c6693.png)

This happened because of version conflicts of node-sass with version<17 of node. I have attacked a table for reference in the next section.

I would also like to mention that node-sass is a [depreciated](https://www.npmjs.com/package/node-sass) package so it should be replaced anyway with [dart-sass](https://www.npmjs.com/package/sass)

### How can we reproduce this bug?

1. Install any Node version less than 17
2. Rebuild node-sass using "npm rebuild node-sass"
3. Then run npm start
4. You will get the same error as in above screenshot

Take a look below for version reference.
![Reference image](https://user-images.githubusercontent.com/39555302/157813217-3599daf2-d0f0-47da-b6b0-27cebfde75ba.png)

### Urgency (Optional)

High priority

**Comment by praveenscience** [comment] 2022-03-11 09:40
Dupe of #91 and it's been fixed.

**Closed by praveenscience** 2022-03-11 09:40 UTC

**Comment by rithgan** [comment] 2022-03-11 16:19
Are you sure it's fully fixed? I reproduced this error today only.

**Comment by praveenscience** [comment] 2022-03-12 18:37
@rithgan Recently no one has reported issues in running the app with the latest code.
