### ISSUE TITLE
Add a section for Work Samples

### ISSUE THREAD

**Issue by csharp489** [CatsInTech/Rezume#43] opened 2020-04-02 07:25 UTC
We should have one more section for **Work Samples**. It consists of 4 elements.
1 Blog Link
2 GitHub Profile
3 Play Store Developer A/c (Public Link)
4 Behance Portfolio Link
5 Other Portfolio Link

This section is important for experience as well as for fresher.
@praveenscience please review it.

**Comment by praveenscience** [comment] 2020-04-02 10:48
Hi @csharp489 That's exactly #15 does, right? This is a duplicate of #15.

**Comment by aryamasinha** [comment] 2020-04-06 11:38
@praveenscience @csharp489  can i take up this issue?

**Comment by rithika-hebbar** [comment] 2020-04-28 16:59
@praveenscience I would like to work on this issue.

**Comment by arpitasahakundu** [comment] 2020-04-29 07:33
i would like to work on this

**Comment by praveenscience** [comment] 2020-04-29 11:03
Sorry all, this is a dupe of #15. 😔

**Closed by praveenscience** 2020-04-29 11:03 UTC
