### ISSUE TITLE
Logo Of the Website & some additional features

### ISSUE THREAD

**Issue by BabyElias** [CatsInTech/Rezume#108] opened 2022-03-10 09:07 UTC
### Is your feature request related to a problem? Please describe.

The website has a very plain , not-so-loud UI/UX interface which is appreciable in the light of its purpose but there is no logo for the website.

 Presently,the user has very limited options to choose from.

The name of the website is Rezume but the name of URL is rezyume.com.

### Describe the solution you'd like.

A logo would definitely help it stand out and be better recognised.

Also,maybe some more templates to choose from can be added for the resume design or maybe some text formatting options can be provided as of now.

Maybe the domain name can be changed if possible.

### Describe alternatives you've considered.

I can create a logo for the website.
Can also add the text formatting options for main content of the resume.
Can't add templates as have no clue about it.

**Comment by praveenscience** [comment] 2022-03-10 13:15
Dupe of #103 #71 and #6

**Closed by praveenscience** 2022-03-10 13:16 UTC

**Comment by praveenscience** [comment] 2022-03-14 22:30
May I assign #6 to you?

**Comment by BabyElias** [comment] 2022-03-15 03:39
Yes Sir, you can assign.
Gaining insights from the discussion on that issue , the logo needs to be:
1)Professional(not having lots of colors or designs,simple)
2) Two sentence format
3) Any slogan or tagline that needs to be added?
