### ISSUE TITLE
 Title: Add Portfolio section in a resume  

### ISSUE THREAD

**Issue by AsmaIbrahimButt** [CatsInTech/Rezume#118] opened 2022-03-23 14:47 UTC
### Is your feature request related to a problem? Please describe.

I want to add the portfolio section in a resume  which can help the recruiters to analyze the different projects of the employee so, that they can easily view the all projects showcase within a single link.

### Describe the solution you'd like.

I will make the cards using reactjs in which there is a details about each section of a project and can view that project easily.And add the filter search option in a portfolio section if a user made many different projects in different tec like html css reactjs the just by using filter option person can easily search to their choice project for view.

### Describe alternatives you've considered.

provide the filter and search option in portfolio section.

### Add any other context or screenshots about the feature request here.

![portfolio](https://user-images.githubusercontent.com/89297894/159726337-a15d8443-357a-4639-bf3b-6b78c133999a.png)

**Comment by AsmaIbrahimButt** [comment] 2022-03-25 12:02
kindly assign me this issue.

**Comment by praveenscience** [comment] 2022-03-27 18:41
Dupe of #15. Come there and let's discuss.

**Closed by praveenscience** 2022-03-27 18:41 UTC
