### ISSUE TITLE
Title:  Implementing the Dummy buttons

### ISSUE THREAD

**Issue by YalfamIamShaon** [CatsInTech/Rezume#112] opened 2022-03-12 06:18 UTC
Hey @praveenscience, I am Shaon Dhar, a GSSOC 22 contributor. I saw your project and loved it. But apart from About and Contact Button, other buttons are not working. So I would like to work on this issue as a GSSOC 22 contributor, 
![Capture](https://user-images.githubusercontent.com/84259582/158006526-1913da42-148a-491a-877e-07f8d5f4d99a.PNG)

**Comment by praveenscience** [comment] 2022-03-12 18:40
Well, this is technically a dupe of #8, did you check that?

**Closed by praveenscience** 2022-03-12 18:40 UTC
